priyanshpatel18/ExpenShare-Web

src/components/SplashScreen.tsx, src/main.tsx
Changed the logic of the splash screen page to make it simpler.   
Fixes #1
https://github.com/priyanshpatel18/ExpenShare-Web/assets/111479342/40a0e3f3-8ec4-479f-a9c9-d4584a6d3efa
=> Fix #1 : splash screen page

src/pages/OtpVerificationPage.tsx
small bug resolved in OtpVerificationPage
=> fix: bug resolved

src/stores/usersStore.tsx
fiexd the bug of registration page not working in first submit.
Fixes# 2
=> fix#2 : Registration Page

src/index.css, src/main.tsx, src/pages/OtpVerificationPage.tsx, src/stores/usersStore.ts
Improved the user authentication process according to the new server.
https://github.com/priyanshpatel18/ExpenShare-Web/assets/111479342/00e7d073-7615-4a2d-b7b2-9d6d66ea01c9
=> feat: User Auth Improvement

package-lock.json, package.json, src/App.tsx, src/main.tsx, src/pages/ForgotPasswordPage.tsx, src/pages/PasswordResetOtpVerificationPage.tsx, src/pages/RegisterOtpVerificationPage.tsx, src/pages/RegistrationPage.tsx, src/pages/ResetPasswordPage.tsx, src/stores/usersStore.ts
implemented Axios in all user authorization pages
https://github.com/priyanshpatel18/ExpenShare-Web/assets/111479342/a7250d08-9039-4a73-8234-c19522c7050a
=> feat/ User Authorization Working

src/components/SideBar.tsx, src/pages/Groups.tsx, src/pages/HomePage.tsx, src/pages/Profile.tsx, src/pages/Transaction.tsx
user data axios added in transactionPage, groupPage, profilePage.
=> feat: feature branch

src/components/HomeScreen.tsx, src/components/SideBar.tsx, src/components/TransactionScreen.tsx, src/index.css, src/main.tsx, src/pages/MainPage.tsx, src/stores/usersStore.ts, vite.config.ts
=> feat: axios added in main page

src/components/SideBar.tsx, src/main.tsx, src/pages/MainPage.tsx
=> fix: bug fixed in main page

src/components/AddTransaction.tsx, src/components/HomeScreen.tsx, src/components/SideBar.tsx, src/components/TransactionScreen.tsx, src/index.css, src/pages/MainPage.tsx, src/pages/RegisterOtpVerificationPage.tsx, src/pages/RegistrationPage.tsx, src/stores/store.ts
fixed bugs created due to changes in store. also improved the style of addTransaction page.
=> fix: Fied bugs

src/components/AddTransaction.tsx, src/index.css, src/pages/MainPage.tsx, src/stores/store.ts
Added invoice input in the add transaction page. Fixed bugs on the add transaction page.
=> feat: added invoice input

src/components/AddTransaction.tsx, src/components/HomeScreen.tsx, src/index.css, src/main.tsx, src/pages/MainPage.tsx, src/stores/store.ts
=> fix: merge conflict resolved

src/components/AddTransaction.tsx, src/components/HomeScreen.tsx, src/components/ProfileScreen.tsx, src/index.css, src/main.tsx, src/stores/store.ts
Logout functionality was added and fixed a small bug in the home screen.
=> feat: Logout functionality added

src/main.tsx
=> fix: server link changed

src/pages/GroupsPage.tsx, src/pages/HomePage.tsx, src/pages/ProfilePage.tsx, src/pages/TransactionsPage.tsx, src/stores/store.ts
fixed bug related to useEffect.
=> fix: fixed bug related to useEffect

src/App.tsx, src/components/AccountScreen.tsx, src/components/HomeScreen.tsx, src/components/ProfileScreen.tsx, src/helper/inputValidation.ts, src/index.css, src/main.tsx, src/pages/AccountPage.tsx, src/stores/store.ts
=> feat: account page added

src/main.tsx
=> fix: server link added

src/index.css
=> addcategary-web

src/App.tsx, src/components/AddGroupMemberScreen.tsx, src/components/AddGroupScreen.tsx, src/components/AddTransaction.tsx, src/components/GroupHomeScreen.tsx, src/components/GroupsScreen.tsx, src/components/HomeScreen.tsx, src/components/Input.tsx, src/components/ProfileScreen.tsx, src/components/SideBar.tsx, src/components/SplashScreen.tsx, src/components/TransactionScreen.tsx, src/components/UserReport.tsx, src/index.css, src/main.tsx, src/pages/DynamicgroupPage.tsx, src/pages/GroupsPage.tsx, src/pages/HomePage.tsx, src/pages/ProfilePage.tsx, src/pages/RegistrationPage.tsx, src/pages/TransactionsPage.tsx, src/stores/store.ts, src/utils/socket.ts
=> dynamicgrouprendering

src/App.tsx, src/components/AddGroupMemberScreen.tsx, src/components/AddGroupTransaction.tsx, src/components/AddTransaction.tsx, src/components/GroupHomeScreen.tsx, src/components/GroupTransactionScreen.tsx, src/components/GroupsScreen.tsx, src/index.css, src/main.tsx, src/pages/DynamicgroupPage.tsx, src/pages/GroupsPage.tsx, src/stores/store.ts, src/utils/socket.ts, vite.config.ts
Group Transaction addition is working. 
Group Transaction Page and a split popup added.
=> feat: Group Transaction addtion is working

src/components/AddGroupMemberScreen.tsx, src/components/GroupHomeScreen.tsx, src/main.tsx, src/stores/store.ts, src/utils/socket.ts
=> feat: getSelectedGroupTransactions added

src/App.tsx, src/components/AddGroupMemberScreen.tsx, src/components/AddGroupTransaction.tsx, src/components/GroupHomeScreen.tsx, src/components/GroupTransactionScreen.tsx, src/index.css, src/stores/store.ts
=> feat: group transaction page working

src/App.tsx, src/components/AddGroupTransaction.tsx, src/components/GroupTransactionScreen.tsx, src/index.css, src/stores/store.ts
=> fix: bug fiexd and updated according to new server controllers

src/App.tsx, src/components/AddTransaction.tsx, src/components/GroupHomeScreen.tsx, src/components/GroupTransactionScreen.tsx, src/stores/store.ts
=> feat: group transaction socket working
